import sys
from datetime import datetime, timezone
from pathlib import Path

import pytest
from sqlalchemy import create_engine
from sqlalchemy.orm import Session, sessionmaker

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))


@pytest.fixture(autouse=True)
def isolated_database(monkeypatch, tmp_path):
    from src.db import session as db_session
    from src.db.models import (
        Base,
        CKANDatasetRecord,
        EUProjectRecord,
        GeoLayerRecord,
        LegislationArticleRecord,
        LegislationEditionRecord,
        ProcurementAwardRecord,
        ProcurementBudgetRecord,
        ProcurementContractRecord,
        ProcurementPlanRecord,
        ProcurementTenderRecord,
        RegistryEntityRecord,
    )

    engine = create_engine(
        f"sqlite:///{tmp_path / 'mddata-test.db'}",
        connect_args={"check_same_thread": False},
        future=True,
    )
    session_factory = sessionmaker(bind=engine, autocommit=False, autoflush=False, class_=Session)

    monkeypatch.setattr(db_session, "engine", engine)
    monkeypatch.setattr(db_session, "SessionLocal", session_factory)

    Base.metadata.create_all(bind=engine)

    now = datetime(2026, 4, 10, tzinfo=timezone.utc)
    with session_factory() as session:
        session.add_all(
            [
                ProcurementTenderRecord(
                    ocid="ocds-md-2026-0001",
                    title="Chisinau road rehabilitation",
                    description="Roadworks and public realm improvements with OCDS-normalized data.",
                    status="active",
                    status_detail="tendering",
                    date_published=now,
                    amount=12500000,
                    currency="MDL",
                    raion="Chisinau",
                    city="Chisinau",
                    buyer_id="md.chisinau",
                    buyer_name="Municipality of Chisinau",
                    buyer_sector="Infrastructure",
                    procurement_method="openTender",
                    procedure_type="openTender",
                    source_url="https://public.mtender.gov.md/tenders/ocds-md-2026-0001",
                    source_modified_at=now,
                    cross_references={"eu_project_ids": ["eu4-urban-001"]},
                    raw_payload={},
                ),
                ProcurementTenderRecord(
                    ocid="ocds-md-2026-0002",
                    title="Cahul school digitalization",
                    description="Connectivity and equipment upgrades for public schools.",
                    status="awarded",
                    date_published=now,
                    amount=4200000,
                    currency="MDL",
                    raion="Cahul",
                    city="Cahul",
                    buyer_id="md.cahul",
                    buyer_name="Cahul District Council",
                    buyer_sector="Education",
                    procurement_method="directAward",
                    procedure_type="directAward",
                    source_url="https://public.mtender.gov.md/tenders/ocds-md-2026-0002",
                    source_modified_at=now,
                    cross_references={"eu_project_ids": ["eu4-edu-014"]},
                    raw_payload={},
                ),
                ProcurementAwardRecord(
                    ocid="award-md-2026-0001",
                    tender_ocid="ocds-md-2026-0001",
                    title="Road rehabilitation award",
                    status="active",
                    amount=11800000,
                    currency="MDL",
                    supplier_name="UrbanRoad SRL",
                    buyer_name="Municipality of Chisinau",
                    buyer_sector="Infrastructure",
                    raion="Chisinau",
                    source_url="https://mtender.gov.md/search/contracts",
                    source_modified_at=now,
                    tags=["award"],
                    raw_payload={},
                ),
                ProcurementContractRecord(
                    ocid="contract-md-2026-0001",
                    award_ocid="award-md-2026-0001",
                    tender_ocid="ocds-md-2026-0001",
                    title="Road rehabilitation contract",
                    status="active",
                    signed_at=now,
                    amount=11800000,
                    currency="MDL",
                    supplier_name="UrbanRoad SRL",
                    buyer_name="Municipality of Chisinau",
                    buyer_sector="Infrastructure",
                    raion="Chisinau",
                    source_url="https://mtender.gov.md/search/contracts",
                    source_modified_at=now,
                    tags=["award"],
                    raw_payload={},
                ),
                ProcurementBudgetRecord(
                    source_id="budget-md-2026-0001",
                    entity_id="ocds-md-2026-0001",
                    title="Infrastructure budget Chisinau",
                    description="",
                    status="planning",
                    amount=22000000,
                    currency="MDL",
                    raion="Chisinau",
                    buyer_name="Municipality of Chisinau",
                    buyer_sector="Infrastructure",
                    planning_from=now,
                    planning_to=now,
                    source_url="https://mtender.gov.md/search/budgets",
                    source_modified_at=now,
                    raw_payload={},
                ),
                ProcurementBudgetRecord(
                    source_id="budget-md-2026-0002",
                    entity_id="ocds-md-2026-0002",
                    title="Education budget Cahul",
                    description="",
                    status="planning",
                    amount=7800000,
                    currency="MDL",
                    raion="Cahul",
                    buyer_name="Cahul District Council",
                    buyer_sector="Education",
                    planning_from=now,
                    planning_to=now,
                    source_url="https://mtender.gov.md/search/budgets",
                    source_modified_at=now,
                    raw_payload={},
                ),
                ProcurementPlanRecord(
                    ocid="plan-md-2026-0001",
                    entity_id="ocds-md-2026-0001",
                    title="Chisinau works plan",
                    status="published",
                    raion="Chisinau",
                    buyer_name="Municipality of Chisinau",
                    buyer_sector="Infrastructure",
                    amount=12500000,
                    currency="MDL",
                    pin=False,
                    tags=["planning"],
                    related_tender_ocids=["ocds-md-2026-0001"],
                    source_url="https://mtender.gov.md/search/plans",
                    source_modified_at=now,
                    raw_payload={},
                ),
                EUProjectRecord(
                    project_id="eu4-urban-001",
                    title="Urban Revitalization in Cahul",
                    description="EU-funded infrastructure project under the Growth Plan.",
                    status="ongoing",
                    sector="Infrastructure",
                    raw_sector="Transport",
                    priority_area="Partnership that creates",
                    subsector="Connectivity (transport & energy)",
                    topic="Transport",
                    countries=["Republic of Moldova"],
                    funding_amount=2300000,
                    currency="EUR",
                    start_date=now,
                    end_date=now,
                    beneficiary="Cahul Municipality",
                    raion="Cahul",
                    region_label="Regional",
                    project_number="429-833",
                    website_url="https://example.test/epic",
                    social_links=[],
                    linked_procurement_ocids=["ocds-md-2026-0002"],
                    source_url="https://eu4moldova.eu/en/projects/eu-project-page/?id=2405",
                    raw_payload={},
                ),
                EUProjectRecord(
                    project_id="eu4-edu-014",
                    title="Digital schools in southern Moldova",
                    description="Connectivity and equipment upgrades for public schools.",
                    status="ongoing",
                    sector="Education",
                    raw_sector="Education",
                    priority_area="Human development",
                    subsector="Education",
                    topic="Schools",
                    countries=["Republic of Moldova"],
                    funding_amount=950000,
                    currency="EUR",
                    start_date=now,
                    end_date=now,
                    beneficiary="Cahul District Council",
                    raion="Cahul",
                    region_label="Regional",
                    project_number="EU4-EDU-014",
                    website_url="https://example.test/education",
                    social_links=[],
                    linked_procurement_ocids=["ocds-md-2026-0002"],
                    source_url="https://eu4moldova.eu/en/projects/eu-project-page/?id=3108",
                    raw_payload={},
                ),
                CKANDatasetRecord(
                    dataset_id="company-register-2026",
                    title="State Register of Legal Entities",
                    slug="company-register-2026",
                    notes="Monthly company register extracted from CKAN.",
                    organization="Government Open Data Portal",
                    tags=["companies", "idno"],
                    resources=[{"id": "res-company-1", "name": "CSV export", "format": "CSV", "url": "https://example.test/company.csv", "mimetype": "text/csv", "datastore_active": False}],
                    source_url="https://date.gov.md/dataset/company-register-2026",
                    raw_payload={},
                ),
                RegistryEntityRecord(
                    entity_key="company:1234567",
                    entity_type="company",
                    entity_id="1234567",
                    name="Example SRL",
                    status="active",
                    description="Example company entry cross-linked to MTender and EU funds.",
                    raion="Chisinau",
                    locality="Chisinau",
                    identifier_label="idno",
                    identifier_value="1234567",
                    source_dataset_id="company-register-2026",
                    source_url="https://date.gov.md/dataset/company-register-2026",
                    cross_references={"tenders": ["ocds-md-2026-0001"], "eu_projects": ["eu4-urban-001"]},
                    raw_payload={},
                ),
                RegistryEntityRecord(
                    entity_key="ngo:7654321",
                    entity_type="ngo",
                    entity_id="7654321",
                    name="Civic Action Moldova",
                    status="active",
                    description="NGO registry entry.",
                    raion="Cahul",
                    locality="Cahul",
                    identifier_label="registration number",
                    identifier_value="7654321",
                    source_dataset_id="ngo-register-2026",
                    source_url="https://date.gov.md/dataset/ngo-register-2026",
                    cross_references={},
                    raw_payload={},
                ),
                LegislationEditionRecord(
                    edition_key="edition-2026-04-10",
                    edition_number="166-169",
                    title="Official Gazette edition 166-169",
                    published_at=now,
                    pdf_url="https://example.test/monitorul.pdf",
                    source_url="https://monitorul.gov.md/",
                    summary="A sample legislative edition.",
                    raw_payload={},
                ),
                LegislationArticleRecord(
                    article_key="edition-2026-04-10:summary",
                    edition_key="edition-2026-04-10",
                    article_number="summary",
                    title="Official Gazette edition 166-169",
                    content_snippet="A sample legislative edition.",
                    source_url="https://example.test/monitorul.pdf",
                    raw_payload={},
                ),
                GeoLayerRecord(
                    layer_key="geospatial-raions",
                    title="Raion boundaries",
                    description="Administrative raion boundaries layer.",
                    source_type="ckan",
                    source_url="https://date.gov.md/dataset/geospatial-raions",
                    layer_metadata={"layer": "raions"},
                    raw_payload={},
                ),
            ]
        )
        session.commit()

    yield
